project:
  type: manuscript

manuscript:
  article: housingstudy.qmd
pdf-engine: xelatex

format:
  html:
    comments:
      hypothesis: true

  # (other formats)
  pdf: default

execute:
  freeze: true