project:
  type: manuscript

manuscript:
  article: housingstudy.qmd
  # title: |
  #   Niobrara Housing Study
  # title-short: Niobrara Housing Study # title-short is used in the pdf head
  # output-file: 2026_niobrara_housing_study # outputs: docs/TufteStyledBook.pdf
  # author: Bobbi Pettit, AICP and Jordan Duffin Wong, Ph.D
  # publisher: FIVE RULE Rural Planning
  # date-format: 06, 2026
  # license: "CC BY"
  # downloads: [pdf]
  # favicon: Images/five_rule_logo.png
# bibliography: references.bib
pdf-engine: xelatex

format:
  html:
    comments:
      hypothesis: true

  # (other formats)
  pdf: default

execute:
  freeze: true



